task1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('registration/',include('user.urls')),
]

user/urls.py
from django.urls import path
from .views import home,doctor,mobile_otp_verification,login,logout

app_name='user'
urlpatterns=[
    path('',home,name="home"),
    path('doctor/',doctor,name="doctor"),
    path('mobile_otp_verification/<slug>/',mobile_otp_verification,name="mobile_otp_verification"),
    path('login/',login,name="login"),
    path('logout/',logout,name="logout"),
]

user/models.py
from math import trunc
from django.db import models
from django.conf import settings
from django.db.models.fields import CharField
from django.contrib.auth.models import User,auth
import random


# Create your models here.
 
class userdetails(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,blank=True,null=True)
    randomid=models.IntegerField(unique=True,default=0)
    number=models.BigIntegerField()
    type=models.CharField(max_length=10)
    mobile_otp=models.IntegerField(default=0)
    email_otp=models.IntegerField(default=0)


    def userdetails(self):
        pass
    def __str__(self):
        return f"{self.user.first_name} {self.type} {self.randomid}"

user/views.py
from django.http.response import HttpResponse
from django.shortcuts import redirect, render,get_object_or_404
from .models import userdetails
from django.contrib.auth.models import User,auth
from django.contrib import messages
from django.core.mail import send_mail
from twilio.rest import Client
import random

# Your Account SID from twilio.com/console
account_sid = "AC1b6527f684e9c359e3dcd87c2da597b8"
# Your Auth Token from twilio.com/console
auth_token  = "a9d6871b0e94268c9c73aa919e799e71"

client = Client(account_sid, auth_token)
# Create your views here.

def home(request):
    if request.method=='POST':
        if request.POST['type']=='doctortype':
               return render(request,"user/doctor.html")
        elif request.POST['type']=='patienttype':
            return render(request,"user/patient.html")   
             
    else:
        return render(request,"user/index.html") 

def doctor(request):
    if request.method=='POST':
        firstname=request.POST['firstname']
        lastname=request.POST['lastname']
        email=request.POST['email']
        password=request.POST['password']
        number=request.POST['number']
        type=request.POST['type']
        mobile_otp=random.randint(100000,999999)
        email_otp=random.randint(1000,9999)
        if User.objects.filter(email=email).exists():
            messages.info(request,'Email Taken')
            return redirect("/registration")
        user=User.objects.create_user(username=email,first_name=firstname,last_name=lastname,email=email,password=password)
        user.save()
        user1=userdetails.objects.create(user=user,number=number,type=type,mobile_otp=mobile_otp,email_otp=email_otp)
        user1.randomid=random.sample(range(10000,99999),1)[0]
        user1.save()
        if type=='doctor':
            user.username="C1"+str(user1.randomid)
            user.save()
        elif type=='patient': 
            user.username="C2"+str(user1.randomid)
            user.save() 

        
        Mmess=f"Welcome to cureya Your otp is {mobile_otp}"
        Emess=f"Welcome to cureya Your otp is {email_otp}"
        send_mail('Welcome',Emess,'ss',[email],fail_silently=False)
        message = client.messages \
        .create(
            body=Mmess,
            from_='+17048692490',
            to=number
        ) 
        return render(request,"user/otp_verification.html",{'user':user,'mobile':False})
         

    

           
           
           
         
def mobile_otp_verification(request,slug):
    otp=request.POST['otp']
    user=User.objects.get(id=slug)
    getusr=userdetails.objects.get(user=slug)
    otptype=request.POST.get('otptype')
    if otptype=='mobile':
        if userdetails.objects.filter(user=user).last().mobile_otp==int(otp):
            messages.success(request,'Mobile number verified succesfully')
            print("yes")
            return render(request,"user/otp_verification.html",{'user':user,'mobile':True})
        else:
            messages.warning(request,'Wrong otp')
            return render(request,"user/otp_verification.html",{'user':user})

    elif otptype=='email':
        user=User.objects.get(id=slug)
        if userdetails.objects.filter(user=user).last().email_otp==int(otp):
            print(user.username)
            msg=f" User created successfully and Mobile number and email both were verified your username is:{user.username}"
            messages.success(request,'User id has been sent your email please use it to login')
            send_mail('Congratulations!',msg,'ss',['harishanbog7@gmail.com'],fail_silently=False)
            return redirect('/registration/login')
            
        else:
            messages.warning(request,'Wrong otp')
            return render(request,"user/otp_verification.html",{'user':user})

def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        try:
            usr=User.objects.get(username=username)
        except:
            messages.info(request,'User doesnot exist please register')
            return redirect('/registration/login')    


        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return HttpResponse("congratulations! you have successfully logged in")

        else:
            messages.info(request,'Invalid Credentials')
            return redirect('/registration/login')    

    else:
        
        return render(request,'user/login.html')

def logout(request):
    auth.logout(request)      
    return redirect('/login')                    




 



    

 

user/templates/user/doctor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  
</head>

<body>
  <h1 class="text-center m-4">Doctor</h1>
  <form method="POST" action="{% url 'user:doctor' %}">
    {%csrf_token%}
    <div class="form-row">
        <div class="col">
            <input type="text" class="form-control" placeholder="First name" value='doctor' name="type" hidden>
          </div>
      <div class="col">
        <input type="text" class="form-control" placeholder="First name" name="firstname" required>
      </div>
      <div class="col">
        <input type="text" class="form-control" placeholder="Last name" name="lastname" required>
      </div>
      <div class="col">
        <input type="email" class="form-control" placeholder="email" name="email" required>
      </div>
      <div class="col">
        <input type="password" class="form-control" placeholder="password" name="password" required>
      </div>
      <div class="col">
        <input type="text" class="form-control" placeholder="number" name="number" max="999999999999" required>
      </div>
      <button class="btn btn-warning">Ok</button>
    </div>
  </form>    
</body>
</html>

user/templates/user/index.html
<html>
    <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    </head>
    <body>
     
  <div>
    {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
  <form action="" method="post">
      {%csrf_token%}
    <div class="form-check">
        <input class="form-check-input" type="radio" name="type" id="exampleRadios1" value="doctortype"  >
        <label class="form-check-label" for="exampleRadios1">
        Doctor
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" type="radio" name="type" id="exampleRadios2" value="patienttype">
        <label class="form-check-label" for="exampleRadios2">
         Patient  </label>
      </div>
      <div>
        <button class="btn btn-primary">Submit</button>
      </div>
  </form>
  <p>Already have an account? <a href="/registration/login/">Login</a></p>

  </div>
  
   
    </body>
  </html>

user/templates/user/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
   
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  />
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</head>
<body>
    
    
    <div allign="center" class="margin" >
        <h1>Logo</h1>
        <div class="bg-white border" style="margin: 10%;">
        <h1 class="">Sign-In</h1>
        {% for message in messages %}
        {{ message }}
        {% endfor %}
    <form action="{% url 'user:login' %}" method="POST" class="container pt-5">
        {% csrf_token %}
        <table class="m-4"> 
            <tr>
                <th><input type="text" name="username" placeholder="email" required><br><br></th>

            </tr>
        <tr>
            <th><input type="password" name="password" placeholder="password" required><br><br></th>
        </tr>
        <tr>
            <th><button type="submit" class="btn btn-warning" name="submit">Submit</button></th>
        </tr>
    </table>
    </form>
    <p class="m-5">Don't have an account? <a href="/registration"> Sign Up</a></p>
</div>
    </div>
 
</body>
</html>

user/templates/user/otp_verification.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {% if not  mobile%}
    <form action="{% url 'user:mobile_otp_verification' user.id %}" method="POST" >
        <h1>Mobile Verification</h1>
        {%csrf_token%}
        <input type="number" name="otp" required>
        <input type="hidden" name="otptype" value="mobile">
       
       
        <button class="btn btn-warning">Verify Mobile number</button>
    </form>
     {%else%}
     <h1>Email verification</h1>
     <form action="{% url 'user:mobile_otp_verification' user.id %}" method="POST">
        {%csrf_token%}
        <input type="number" name="otp" requi>
        <input type="hidden" name="otptype" value="email">
       
        <input type="hidden" name="user1" value="{{user1.id}}">

        
        <button class="btn btn-warning">Verify Email number</button>
    </form>
     {%endif%}   
</body>
</html>

user/templates/user/patient.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  
</head>

<body>
  <h1 class="text-center m-4">Patient</h1>
  <form method="POST" action="{% url 'user:doctor' %}">
    {%csrf_token%}
    <div class="form-row">
        <div class="col">
            <input type="text" class="form-control" placeholder="First name" value='patient' name="type" hidden>
          </div>
      <div class="col">
        <input type="text" class="form-control" placeholder="First name" name="firstname" required>
      </div>
      <div class="col">
        <input type="text" class="form-control" placeholder="Last name" name="lastname" required>
      </div>
      <div class="col">
        <input type="email" class="form-control" placeholder="email" name="email" required>
      </div>
      <div class="col">
        <input type="password" class="form-control" placeholder="password" name="password" required>
      </div>
      <div class="col">
        <input type="text" class="form-control" placeholder="number" name="number" required>
      </div>
      <button class="btn btn-warning">Ok</button>
    </div>
  </form>    
</body>
</html>